### ISSUE TITLE
FR: add exceptions to ignore

### ISSUE THREAD

**Issue by chrisgrieser** [Ummler/obsidian-auto-correct-capitals#1]
Thanks for this nice little plugin!

There are a few minor edge cases that I noticed, which are "false positives", meaning the plugin is triggered even though those are actually correct:
- `FRs` (Feature Requests)
- `PRs` (Pull Requests)

There are probably some more, when looking at specific languages. A solution to this I can think of is to add a simple setting, where the user can define some custom words to ignore.

**Comment by Ummler** [comment]
Good idea! I'll add this setting soon :)

**Comment by KillyMXI** [comment]
I also need this.
I have some exceptions that only make sense for me.

**Comment by Ummler** [comment]
The update is now available in the Obsidian plugin browser. Also fixed a bug where if a word starts with a diacritical character ('Ä' for example) it would not be recognized as part of the word.
