### ISSUE TITLE
Code blocks, interfaces

### ISSUE THREAD

**Issue by KillyMXI** [Ummler/obsidian-auto-correct-capitals#2]
Consider following markdown note content:

````markdown
A line containing `ISomething` interface name.

```csharp
interface ISomething : IBase
{
  // code containing interface names
}
```
````

Plugin tries to autocorrect them, and this is not something I need.
Adding any possible names to exceptions is not viable solution.

Perhaps most reasonable solution here - (an option for) not autocorrecting inside code blocks, both inline and multiline.

Other solution that might work in different situations, including when I'm not opening a code block before typing in the interface name - ability to define exceptions as regular expressions.

**Comment by Ummler** [comment]
Being able to switch off the correction in code blocks is a good idea. I'll take care of that soon

**Comment by Ummler** [comment]
i disabled auto correction in multiline code blocks and inline code blocks now

**Comment by KillyMXI** [comment]
Thank you
